apiVersion: v1
kind: Service # Defines to create Service type Object
metadata:
  name: my-nginx-demo-service
spec:
  selector:
    name: deployment-custom-label   # Apply this service to any pods which has the specific label
  ports:
    - protocol: TCP
      port: 80    # Containers port exposed
      targetPort: 80  # Pods port
      nodePort: 30080
  type: NodePort # Specifies the service type i.e ClusterIP or NodePort
