# postgres-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: your-db-username
            - name: POSTGRES_PASSWORD
              value: your-db-password
            - name: POSTGRES_DB
              value: your-db-name
          ports:
            - containerPort: 5432
